version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: taskmaster
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
